# Generated by Django 5.0.6 on 2024-05-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
