# Generated by Django 5.0.6 on 2024-05-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_product_category_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
