# Generated by Django 5.0.6 on 2024-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_remove_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
