# Generated by Django 5.0.6 on 2024-05-15 09:46

from django.db import migrations, models
import datetime

def set_default_registration_date(apps, schema_editor):
    Signup = apps.get_model('new', 'Signup')
    today = datetime.date.today()
    Signup.objects.all().update(registration_date=today)


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_registration_date),
    ]
