# Generated by Django 5.0.6 on 2024-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='registration_date',
            field=models.DateField(default=False),
        ),
    ]
