# Generated by Django 5.0.6 on 2024-05-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_alter_signup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='registration_date',
        ),
    ]
