# Generated by Django 5.0.6 on 2024-05-15 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0012_remove_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
